---
version: '3.6'
services:
  wg-portal:
    image: h44z/wg-portal:2.0.0-alpha1
    container_name: wg-portal
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
    environment:
      - EXTERNAL_URL=http://localhost:8888
